export EDITOR='nvim'
export DIFFPROG='nvim -d'
export VISUAL='nvim'
export PAGER='less'
export GOPATH="$HOME/go"
export GPG_TTY=$(tty)
export LESS='-iMRS -x2'
export SYSTEMD_LESS='FRXMK'

# bat
export BAT_PAGER="less -RS"
export BAT_THEME="OneHalfDark"

# NNN
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Wayland
export LIBVA_DRIVER_NAME=iHD
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

export NO_AT_BRIDGE=1
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1



pathappend() {
  for ARG in "$@"
  do
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="${PATH:+"$PATH:"}$ARG"
    fi
  done
}

pathappend "$HOME/dotfiles/bin" "$GOPATH/bin" "$HOME/.local/bin"

if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
  exec sway > /var/log/sway.log 2>&1
fi

[[ -f ~/.bashrc ]] && . ~/.bashrc
