# If not running interactively, don't do anything
[[ $- != *i* ]] && return

eval "$(starship init bash)"

alias ls="exa"
alias ll="exa --icons --git -la"
alias tree="exa --icons --tree"

alias cat="bat"
alias find="fd"

