#!/bin/zsh

zmodules=(archive utility directory environment input git history \
  syntax-highlighting history-substring-search autosuggestions prompt completion)
zprompt_theme='lean'
SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '
ztermtitle='%~'
# Set to vi or emacs
zinput_mode='emacs'
zdouble_dot_expand='true'
zhighlighters=(main brackets cursor)

