#!/bin/zsh

zmodules=(directory environment git history input archive utility \
  autosuggestions prompt completion syntax-highlighting history-substring-search)
zprompt_theme='pure'
ztermtitle='%m:%~'
# Set to vi or emacs
zinput_mode='emacs'
zhighlighters=(main brackets pattern cursor)
