#!/usr/bin/zsh

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export GOPATH="$HOME/go"
export GPG_TTY=$(tty)
export LESS='-F -g -i -M -R -S -w -X -z-4'

typeset -gU cdpath fpath mailpath path
path+=("$HOME/dotfiles/bin" "$GOPATH/bin")

# Change default zim location
export ZIM_HOME=${HOME}/dotfiles/shell/zimfw

# Initialize zim
[[ -s ${ZIM_HOME}/login_init.zsh ]] && source ${ZIM_HOME}/login_init.zsh

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx
fi

