#!/usr/bin/zsh

export EDITOR='nvim'
export DIFFPROG='nvim -d'
export VISUAL='nvim'
export PAGER='less'
export GOPATH="$HOME/go"
export GPG_TTY=$(tty)
export LESS='-F -g -i -M -R -S -w -X -z-4'
export SYSTEMD_LESS='FRXMK'

typeset -gU cdpath fpath mailpath path
path+=("$HOME/dotfiles/bin" "$GOPATH/bin" "$HOME/.local/bin")

# Change default zim location
export ZIM_HOME=${HOME}/dotfiles/shell/zimfw

# Initialize zim
[[ -s ${ZIM_HOME}/login_init.zsh ]] && source ${ZIM_HOME}/login_init.zsh

if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

# if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  # exec startx > ${HOME}/.xoutput 2>&1
# fi

