#!/usr/bin/env bash

#{{{ Repo
acpi
acpi_call
acpid
chromium
ctags
ffmpegthumbnailer
file-roller
fish
ghostscript
git
gnome-disk-utility
go
gvfs-mtp
i3lock
neovim
network-manager-applet
networkmanager-openvpn
noto-fonts
noto-fonts-emoji
pcmanfm-gtk3
powerline-fonts
python-neovim
redshift
rofi
scrot
shellcheck
sxiv
syncthing
syncthing-inotify
tabbed
thermald
tlp
transmission-gtk
unrar
unzip
vicious
xorg-xkill
xsel
youtube-dl
zathura-pdf-mupdf
#}}}

#{{{ AUR
browserpass
capitaine-cursors
cmus-git
la-capitaine-icon-theme-git
mpv-light
neovim-symlinks
qt5-styleplugins
ttf-mensch
xss-lock
xst-git
#}}}

