#!/bin/sh
# Generated using
# code --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension 42Crunch.vscode-openapi
code --install-extension ahmadawais.shades-of-purple
code --install-extension batisteo.vscode-django
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension donjayamanne.python-extension-pack
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension evilz.vscode-reveal
code --install-extension felipecaputo.git-project-manager
code --install-extension foxundermoon.shell-format
code --install-extension golang.Go
code --install-extension Gruntfuggly.todo-tree
code --install-extension James-Yu.latex-workshop
code --install-extension Koihik.vscode-lua-format
code --install-extension liviuschera.noctis
code --install-extension magicstack.MagicPython
code --install-extension mermade.openapi-lint
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cpptools
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension RobbOwen.synthwave-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sumneko.lua
code --install-extension teabyii.ayu
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension wholroyd.jinja
