#!/bin/bash
code --install-extension ahmadawais.shades-of-purple
code --install-extension bierner.markdown-preview-github-styles
code --install-extension christian-kohler.path-intellisense
code --install-extension foxundermoon.shell-format
code --install-extension Gruntfuggly.todo-tree
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sumneko.lua
code --install-extension vscodevim.vim
