default-key 04512E1527A264A3B5519960EAA0A25A43D3DBE0

# Behavior
no-emit-version
no-comments
keyid-format 0xlong
with-fingerprint
require-cross-certification
no-symkey-cache
charset utf-8

# Algorithms and ciphers
personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256
personal-compress-preferences ZLIB BZIP2 ZIP Uncompressed
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512
s2k-digest-algo SHA512
s2k-cipher-algo AES256
