-- Light Owl companion for oxfist/night-owl.nvim.
-- Palette derived from sdras/night-owl's official Light Owl theme.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "light"
vim.o.termguicolors = true
vim.g.colors_name = "light-owl"

local c = {
  bg = "#FBFBFB",
  bg_alt = "#F0F0F0",
  bg_soft = "#F6F6F6",
  fg = "#403f53",
  dark = "#111111",
  muted = "#989fb1",
  border = "#d9d9d9",
  cursor = "#90A7B2",
  selection = "#E0E0E0",
  selection_active = "#d3e8f8",
  selection_inactive = "#E0E7EA",
  word = "#D2E6F8",
  word_strong = "#A3CFE9",
  blue = "#4876d6",
  purple = "#994cc3",
  cyan = "#0c969b",
  red = "#bc5454",
  orange = "#c96765",
  magenta = "#aa0982",
  green = "#08916a",
  yellow = "#daaa01",
  error = "#E64D49",
  added = "#49d0c5",
  changed = "#6fbef6",
  deleted = "#f76e6e",
}

local groups = {
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.bg_alt },
  SignColumn = { bg = c.bg },
  Folded = { fg = c.muted, bg = c.bg_alt },
  FoldColumn = { fg = c.muted, bg = c.bg },
  Pmenu = { fg = c.fg, bg = c.bg_alt },
  PmenuSel = { fg = c.fg, bg = c.selection_active },
  PmenuSbar = { bg = c.bg_soft },
  PmenuThumb = { bg = c.cursor },
  FloatBorder = { fg = c.border, bg = c.bg_alt },
  FloatTitle = { fg = c.purple, bg = c.bg_alt, bold = true },
  Whitespace = { fg = c.border },
  VertSplit = { fg = c.border },
  WinSeparator = { fg = c.border },
  LineNr = { fg = c.cursor },
  CursorLineNr = { fg = c.fg, bold = true },
  CursorLine = { bg = c.bg_alt },
  CursorColumn = { bg = c.bg_alt },
  ColorColumn = { bg = c.bg_alt },
  Cursor = { fg = c.bg, bg = c.cursor },
  lCursor = { fg = c.bg, bg = c.cursor },
  CursorIM = { fg = c.bg, bg = c.cursor },
  TermCursor = { fg = c.bg, bg = c.cursor },
  Visual = { bg = c.selection },
  Search = { bg = "#CFD4D4" },
  IncSearch = { bg = c.added },
  CurSearch = { bg = c.added },
  MatchParen = { bg = c.selection_active, bold = true },
  QuickFixLine = { bg = c.selection_active },
  StatusLine = { fg = c.fg, bg = c.bg_alt },
  StatusLineNC = { fg = c.muted, bg = c.bg_soft },
  TabLine = { fg = c.fg, bg = c.bg_alt },
  TabLineSel = { fg = c.fg, bg = c.bg_soft, bold = true },
  TabLineFill = { bg = c.bg_alt },
  Directory = { fg = c.blue },
  Title = { fg = c.blue, bold = true },
  Conceal = { fg = c.cursor },
  NonText = { fg = c.muted },
  SpecialKey = { fg = c.muted },

  Comment = { fg = c.muted, italic = true },
  String = { fg = c.blue },
  Character = { fg = c.orange },
  Number = { fg = c.magenta },
  Float = { fg = c.magenta },
  Boolean = { fg = c.red, italic = true },
  Constant = { fg = c.blue, italic = true },
  Identifier = { fg = c.cyan },
  Function = { fg = c.blue, italic = true },
  Statement = { fg = c.purple, italic = true },
  Conditional = { fg = c.purple },
  Repeat = { fg = c.purple },
  Label = { fg = c.cyan },
  Operator = { fg = c.cyan },
  Keyword = { fg = c.purple },
  Exception = { fg = c.purple },
  Include = { fg = c.purple, italic = true },
  PreProc = { fg = c.purple },
  Define = { fg = c.purple },
  Macro = { fg = c.purple },
  Type = { fg = c.blue, italic = true },
  StorageClass = { fg = c.purple, italic = true },
  Structure = { fg = c.dark },
  Typedef = { fg = c.blue },
  Special = { fg = c.cyan },
  SpecialChar = { fg = c.magenta },
  Tag = { fg = c.purple },
  Delimiter = { fg = c.fg },
  Underlined = { fg = c.blue, underline = true },
  Error = { fg = c.error },
  ErrorMsg = { fg = c.error },
  WarningMsg = { fg = c.yellow },
  Todo = { fg = c.bg, bg = c.blue, bold = true },

  DiffAdd = { fg = c.fg, bg = c.added },
  DiffChange = { fg = c.fg, bg = c.changed },
  DiffDelete = { fg = c.fg, bg = c.deleted },
  DiffText = { fg = c.fg, bg = c.selection_active, bold = true },

  ["@nowl.constant.builtin.na.r"] = { fg = c.red, italic = true },
  ["@nowl.constant.builtin.null"] = { fg = c.red },
  ["@nowl.indentChar"] = { fg = c.border, nocombine = true },
  ["@nowl.indentChar.active"] = { fg = c.cursor, nocombine = true },
  ["@nowl.keyword.break"] = { link = "Statement" },
  ["@nowl.keyword.operator.new.javascript"] = { fg = c.cyan },
  ["@nowl.punctuation.string.delimiter"] = { fg = c.dark, nocombine = true },
  ["@nowl.variable.object"] = { fg = c.cyan, italic = true },
  ["@nowl.variable.parameter.option.bash"] = { fg = c.blue },
  ["@nowl.visual.active"] = { bg = c.selection },
  ["@nowl.visual.inactive"] = { bg = c.selection_inactive },

  ["@comment"] = { link = "Comment" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = c.magenta },
  ["@string.regex"] = { fg = c.blue },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@number.float"] = { link = "Float" },
  ["@boolean"] = { link = "Boolean" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Constant" },
  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.cyan, italic = true },
  ["@variable.parameter"] = { fg = c.cyan },
  ["@property"] = { fg = c.cyan },
  ["@field"] = { fg = c.cyan },
  ["@function"] = { link = "Function" },
  ["@function.call"] = { fg = c.blue },
  ["@function.builtin"] = { fg = c.blue },
  ["@function.method"] = { fg = c.blue, italic = true },
  ["@constructor"] = { fg = c.blue },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.function"] = { link = "Statement" },
  ["@keyword.operator"] = { fg = c.cyan },
  ["@keyword.return"] = { link = "Statement" },
  ["@operator"] = { link = "Operator" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = c.blue },
  ["@type.class"] = { fg = c.dark },
  ["@module"] = { fg = c.dark },
  ["@attribute"] = { fg = c.blue, italic = true },
  ["@tag"] = { fg = c.purple },
  ["@tag.attribute"] = { fg = c.blue, italic = true },
  ["@tag.delimiter"] = { fg = c.purple },
  ["@punctuation.bracket"] = { fg = c.fg },
  ["@punctuation.delimiter"] = { fg = c.fg },
  ["@punctuation.special"] = { fg = c.cyan },
  ["@markup.heading"] = { fg = c.blue, bold = true },
  ["@markup.strong"] = { fg = c.blue, bold = true },
  ["@markup.italic"] = { fg = c.purple, italic = true },
  ["@markup.raw"] = { fg = c.cyan },
  ["@markup.link"] = { fg = c.blue, underline = true },

  DiagnosticError = { fg = c.error },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticUnderlineError = { sp = c.error, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
  LspInfoBorder = { fg = c.border },
  LspInlayHint = { fg = c.fg, bg = c.bg_alt },

  GitSignsAdd = { fg = c.added },
  GitSignsChange = { fg = c.changed },
  GitSignsDelete = { fg = c.deleted },
  GitGutterAdd = { fg = c.added },
  GitGutterChange = { fg = c.changed },
  GitGutterDelete = { fg = c.deleted },
  TelescopeSelection = { bg = c.selection_active },
  TelescopeMatching = { fg = c.blue, bold = true },
  TelescopeBorder = { fg = c.border },
  NvimTreeNormal = { fg = c.fg, bg = c.bg_alt },
  NvimTreeNormalNC = { fg = c.muted, bg = c.bg_alt },
  NvimTreeIndentMarker = { fg = c.border },
  NvimTreeCursorLine = { bg = c.selection_active },
  NvimTreeRootFolder = { fg = c.purple, bold = true },
  IblIndent = { fg = c.border },
  IblScope = { fg = c.cursor },
  IndentBlanklineChar = { fg = c.border },
  IndentBlanklineContextChar = { fg = c.cursor },
  IlluminatedWordText = { bg = c.word },
  IlluminatedWordRead = { bg = c.word },
  IlluminatedWordWrite = { bg = c.word_strong },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
