#!/usr/bin/env lua

local lgi = require 'lgi'
local Gtk = lgi.require('Gtk', '3.0')
local os = os

local action_list = {}
local to_execute = {}
local res_folder = os.getenv("RESDIR") or os.getenv("HOME").."/awmdotfiles/res"

function on_check_button_toggled(checkbutton)
    local label = checkbutton:get_label()

    if checkbutton:get_active() then
        to_execute[label] = action_list[label]
    else
        to_execute[label] = nil
    end
end

function on_restore_click(button)
    actioncmd = res_folder.."/scripts"
    for i, action in pairs(to_execute) do
        actioncmd = actioncmd .. " ".. action
    end
    success = os.execute(actioncmd)
    if success then
        os.execute("notify-send 'Restore Successful'")
    end
    os.exit(0)
end

function create_checkbox(name)
    local checkbutton = Gtk.CheckButton{
        label = name,
        on_toggled = on_check_button_toggled
    }
    return checkbutton
end

local window = Gtk.Window{
    title = 'CheckButton',
    on_destroy = Gtk.main_quit,
    resizable = false,
    gravity = 4,
    default_width = 200,
    window_position = 1
}

local vbox = Gtk.Box{
    orientation = 'VERTICAL'
}
window:add(vbox)

local label = Gtk.Label{
    label = 'Restore Utility'
}
vbox:pack_start(label, false, false, 0)

local listbox = Gtk.ListBox{}
vbox:pack_start(listbox, false, false, 0)

local btn_restore = Gtk.Button{
    label = 'Restore',
    on_clicked = on_restore_click
    }
vbox:pack_start(btn_restore, false, false, 0)

local header_file,err = io.open( res_folder.. "/header" )
if err then print("Unable to Open File"); return; end

while true do
    line = header_file:read()
    if line == nil then break end
    for k, v in string.gmatch(line, "(%w[%w ]*):(%w+)") do
        action_list[k] = v
        local checkbutton = create_checkbox(k)
        listbox:insert(checkbutton, -1)
    end
end

header_file:close()
window:show_all()

Gtk:main()

